### ISSUE TITLE
Broken signup

### ISSUE THREAD

**Issue by chalu** [Anyitechs/fsi_frontend#2]
User signup seems broken. 

You might want to send the BVN number to your backend and use the [NIBSS SDK](https://github.com/fsi-sandbox/fsi-sdk-javascript/tree/main/lib/nibss) on the server-side to handle BVN validation/auth, and then return a suitable response to your frontend app

**Comment by Anyitechs** [comment]
Acknowledged. I will fix that.

**Comment by Anyitechs** [comment]
There seems to be an issue with the SDK, it doesn't verify a valid BVN but it works fine on the test BVN provided on the README.md file. I tried my BVN but it I got an error response of `name: ApiErrors`, and a 400 bad request status code. I've debugged and concluded that this isn't an issue on my side but on the API itself. 

What do you think/advice I do? I have the API up and I consumed on the frontend too but it only verifies test bvn but not a valid bvn.

**Comment by chalu** [comment]
Kindly proceed with using the sample BVN from the sandbox doxumentation.

**Comment by Anyitechs** [comment]
Okay. Thanks.
