### ISSUE TITLE
No Codacy code quality badge

### ISSUE THREAD

**Issue by chalu** [Anyitechs/fsi_frontend#3]
Integrate a code quality badge from Codacy into this repo's README file. Take a look at [this repo (e.g its README file)](https://github.com/chalu/smart-search) for a sample of how a repo with Codacy integration looks like. 

You can [start from here](https://github.com/marketplace/codacy)

Once integrated, you will get a public/transparent [code quality report like this over here](https://app.codacy.com/gh/chalu/smart-search/dashboard)

**Comment by Anyitechs** [comment]
Acknowledged. I will integrate that sir.
